repos:
  - repo: local
    hooks:
      - id: mise-lint
        name: mise lint
        entry: mise run lint
        language: system
        pass_filenames: false
      - id: sort-nix-lists
        name: sort nix lists
        entry: python scripts/sort_nix_lists.py --fail-on-change --files
        language: system
        files: '\.nix$'
        pass_filenames: true
      - id: prepare-commit-msg
        name: prepare-commit-msg
        entry: uvx cmtr@latest prepare-commit-msg
        language: system
        stages: [prepare-commit-msg]
